name: pickle-env
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.10
  - pip
  - pip:
      - opencv-python>=4.7.0
      - torch>=2.0.0
      - torchvision>=0.15.0
      - torchaudio>=2.0.0
      - ultralytics>=8.0.0
      - matplotlib>=3.7.0
      - mlflow>=2.8.0
      - pyyaml>=6.0
      - tqdm>=4.65.0
      - rich>=13.0.0
      - pandas>=1.5.3
      - scikit-learn>=1.2.0
      - boto3>=1.26.0
      - seaborn>=0.12.0
      - streamlit>=1.24.0
      - plotly>=5.13.0
      - click>=8.1.3 