version: '3.9'

services:
  api:
    build: .
    container_name: pickleball-llm
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    runtime: nvidia
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
