version: '3.8'

services:
  dashboard:
    build: .
    ports:
      - "8501:8501"
    volumes:
      - ./data:/app/data
      - ./config:/app/config
    environment:
      - PYTHONPATH=/app/src
    command: streamlit run src/pickleball_vision/dashboard/app.py --server.address 0.0.0.0 