groups:
  - name: pickleball_vision_alerts
    rules:
      - alert: HighErrorRate
        expr: rate(http_requests_total{status=~"5.."}[5m]) > 0.1
        for: 5m
        labels:
          severity: critical
        annotations:
          summary: High error rate detected
          description: "Error rate is {{ $value }} for the last 5 minutes"

      - alert: SlowResponseTime
        expr: http_request_duration_seconds{quantile="0.9"} > 2
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: Slow response times detected
          description: "90th percentile of response time is {{ $value }}s"

      - alert: HighMemoryUsage
        expr: (container_memory_usage_bytes / container_memory_limit_bytes) * 100 > 85
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: High memory usage
          description: "Container memory usage is {{ $value }}%"

      - alert: HighCPUUsage
        expr: rate(container_cpu_usage_seconds_total[5m]) * 100 > 80
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: High CPU usage
          description: "Container CPU usage is {{ $value }}%"

      - alert: VectorDBDown
        expr: up{job="vector-db"} == 0
        for: 1m
        labels:
          severity: critical
        annotations:
          summary: Vector DB is down
          description: "Vector DB has been down for more than 1 minute"

      - alert: RedisDown
        expr: up{job="redis"} == 0
        for: 1m
        labels:
          severity: critical
        annotations:
          summary: Redis is down
          description: "Redis has been down for more than 1 minute" 